services:
  backend:
    build:
      context: backend
    restart: always
    entrypoint: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs:/app/logs
    env_file:
      - backend/.env

  frontend:
    build:
      context: frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
