/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutMyProjectsRouteImport } from './routes/_layout.my-projects'
import { Route as LayoutHackathonsRouteImport } from './routes/_layout.hackathons'
import { Route as LayoutExperienceRouteImport } from './routes/_layout.experience'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyProjectsRoute = LayoutMyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHackathonsRoute = LayoutHackathonsRouteImport.update({
  id: '/hackathons',
  path: '/hackathons',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperienceRoute = LayoutExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/experience': typeof LayoutExperienceRoute
  '/hackathons': typeof LayoutHackathonsRoute
  '/my-projects': typeof LayoutMyProjectsRoute
}
export interface FileRoutesByTo {
  '/experience': typeof LayoutExperienceRoute
  '/hackathons': typeof LayoutHackathonsRoute
  '/my-projects': typeof LayoutMyProjectsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/experience': typeof LayoutExperienceRoute
  '/_layout/hackathons': typeof LayoutHackathonsRoute
  '/_layout/my-projects': typeof LayoutMyProjectsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experience' | '/hackathons' | '/my-projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/experience' | '/hackathons' | '/my-projects' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/experience'
    | '/_layout/hackathons'
    | '/_layout/my-projects'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-projects': {
      id: '/_layout/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof LayoutMyProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hackathons': {
      id: '/_layout/hackathons'
      path: '/hackathons'
      fullPath: '/hackathons'
      preLoaderRoute: typeof LayoutHackathonsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experience': {
      id: '/_layout/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof LayoutExperienceRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutExperienceRoute: typeof LayoutExperienceRoute
  LayoutHackathonsRoute: typeof LayoutHackathonsRoute
  LayoutMyProjectsRoute: typeof LayoutMyProjectsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutExperienceRoute: LayoutExperienceRoute,
  LayoutHackathonsRoute: LayoutHackathonsRoute,
  LayoutMyProjectsRoute: LayoutMyProjectsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
