/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutProjectsRouteImport } from './routes/_layout.projects'
import { Route as LayoutProjectSlugRouteImport } from './routes/_layout.project.$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectSlugRoute = LayoutProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/projects': typeof LayoutProjectsRoute
  '/project/$slug': typeof LayoutProjectSlugRoute
}
export interface FileRoutesByTo {
  '/projects': typeof LayoutProjectsRoute
  '/': typeof LayoutIndexRoute
  '/project/$slug': typeof LayoutProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/project/$slug': typeof LayoutProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/projects' | '/' | '/project/$slug'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/projects'
    | '/_layout/'
    | '/_layout/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/project/$slug': {
      id: '/_layout/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof LayoutProjectSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutProjectsRoute: typeof LayoutProjectsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectSlugRoute: typeof LayoutProjectSlugRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProjectsRoute: LayoutProjectsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectSlugRoute: LayoutProjectSlugRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
