"""Initial

Revision ID: 7c8f000c6729
Revises: 
Create Date: 2026-10-05 18:16:22.016243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8f000c6729'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('telegram_accounts',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contact_requests',
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('email_account_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_account_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telegram_account_id'], ['telegram_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_requests_email_account_id'), 'contact_requests', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_contact_requests_telegram_account_id'), 'contact_requests', ['telegram_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_requests_telegram_account_id'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_email_account_id'), table_name='contact_requests')
    op.drop_table('contact_requests')
    op.drop_table('telegram_accounts')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
